/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.ImageIcon;
import logica.Calculadora;

/**
 *
 * @author Eduard Paez
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        jLLogo.setIcon(new ImageIcon("Logo.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRBHombre = new javax.swing.JRadioButton();
        jRBMujer = new javax.swing.JRadioButton();
        jSliderEstatura = new javax.swing.JSlider();
        jSliderMasa = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jTFEstatura = new javax.swing.JTextField();
        jTFMasa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBCalcular = new javax.swing.JButton();
        jLLogo = new javax.swing.JLabel();
        jLIMC = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLRecomendacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CALCULADORA IMC - IUDIGITAL");

        buttonGroup1.add(jRBHombre);
        jRBHombre.setSelected(true);
        jRBHombre.setText("Hombre");
        jRBHombre.setActionCommand("M");

        buttonGroup1.add(jRBMujer);
        jRBMujer.setText("Mujer");
        jRBMujer.setActionCommand("F");

        jSliderEstatura.setMaximum(220);
        jSliderEstatura.setMinimum(100);
        jSliderEstatura.setValue(120);
        jSliderEstatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderEstaturaStateChanged(evt);
            }
        });

        jSliderMasa.setMaximum(500);
        jSliderMasa.setMinimum(30);
        jSliderMasa.setValue(40);
        jSliderMasa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderMasaStateChanged(evt);
            }
        });
        jSliderMasa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSliderMasaFocusLost(evt);
            }
        });

        jLabel2.setText("Altura (cm)");

        jTFEstatura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFEstaturaFocusLost(evt);
            }
        });

        jTFMasa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFMasaFocusLost(evt);
            }
        });

        jLabel3.setText("Masa (kg)");

        jBCalcular.setText("Calcula tu índice de masa corporal (IMC)");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLIMC.setText("-");

        jLEstado.setText("-");

        jLRecomendacion.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSliderEstatura, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(jSliderMasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFEstatura)
                                    .addComponent(jTFMasa, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRBHombre)
                                        .addGap(27, 27, 27)
                                        .addComponent(jRBMujer))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jBCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLEstado)
                                                    .addComponent(jLIMC)
                                                    .addComponent(jLRecomendacion))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBHombre)
                    .addComponent(jRBMujer))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jSliderEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jBCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLIMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLEstado)
                        .addGap(18, 18, 18)
                        .addComponent(jLRecomendacion)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(jLLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        double masaCorporal = Double.parseDouble(jTFMasa.getText());
        double estatura = Double.parseDouble(jTFEstatura.getText());
        double IMC = Calculadora.calcularIMC(masaCorporal, estatura);
        char genero = buttonGroup1.getSelection().getActionCommand().charAt(0);
        mostrarIMC("su IMC es: " + IMC);
        mostrarEstado(genero, IMC);
        mostrarPesoIdeal(genero, estatura);
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void mostrarIMC (String msjIMC){
        jLIMC.setText(msjIMC); 
    }
    
    private void mostrarEstado (char genero, double IMC){
        String estado = Calculadora.calcularEstado(genero, IMC);
        jLEstado.setText("Tienes: " + estado);
    }
    
    private void mostrarPesoIdeal (char genero, double estatura){
        String pesoIdeal = Calculadora.calcularPesoIdeal(genero, estatura);
        jLRecomendacion.setText(pesoIdeal);
    }
    
    private void jSliderEstaturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderEstaturaStateChanged
        // TODO add your handling code here:
        jTFEstatura.setText(String.valueOf(jSliderEstatura.getValue()));
    }//GEN-LAST:event_jSliderEstaturaStateChanged

    private void jTFEstaturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEstaturaFocusLost
        // TODO add your handling code here:
        if (!jTFEstatura.getText().isBlank() && !jTFEstatura.getText().isEmpty()){
            jSliderEstatura.setValue((int)Double.parseDouble(jTFEstatura.getText()));
        }else{
            jSliderEstatura.setValue(0);
        }
    }//GEN-LAST:event_jTFEstaturaFocusLost

    private void jSliderMasaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSliderMasaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jSliderMasaFocusLost

    private void jSliderMasaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderMasaStateChanged
        // TODO add your handling code here:
        jTFMasa.setText(String.valueOf(jSliderMasa.getValue()));
    }//GEN-LAST:event_jSliderMasaStateChanged

    private void jTFMasaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMasaFocusLost
        // TODO add your handling code here:
        if (!jTFMasa.getText().isBlank() && !jTFMasa.getText().isEmpty()){
            jSliderMasa.setValue((int)Double.parseDouble(jTFMasa.getText()));
        }else{
            jSliderMasa.setValue(0);
        }
    }//GEN-LAST:event_jTFMasaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLIMC;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLRecomendacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBHombre;
    private javax.swing.JRadioButton jRBMujer;
    private javax.swing.JSlider jSliderEstatura;
    private javax.swing.JSlider jSliderMasa;
    private javax.swing.JTextField jTFEstatura;
    private javax.swing.JTextField jTFMasa;
    // End of variables declaration//GEN-END:variables
}
